// Player
export const ADD_PLAYER_POKEMON = 'ADD_PLAYER_POKEMON';
export const REDUCE_PLAYER_HEALTH = 'REDUCE_PLAYER_HEALTH';
export const CONSUME_ITEM = 'CONSUME_ITEM';
export const INCREASE_HEALTH = 'INCREASE_HEALTH';
export const GAIN_EXPERIENCE = 'GAIN_EXPERIENCE';
export const POKEMON_EVOLVED = 'POKEMON_EVOLVED';
export const UPDATE_ACTIVE_POKEMON = 'UPDATE_ACTIVE_POKEMON';
export const REVIVE_POKEMON = 'REVIVE_POKEMON';
export const RESET_ACTIVE_POKEMON = 'RESET_ACTIVE_POKEMON';

// Opponent
export const ADD_OPP_POKEMON = 'ADD_OPP_POKEMON';
export const REDUCE_OPP_HEALTH = 'REDUCE_OPP_HEALTH';
export const RESET_OPPONENT = 'RESET_OPPONENT';
export const SWITCH_OPP_POKEMON = 'SWITCH_OPP_POKEMON';

// Town
export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';

// Status
export const UPDATE_PROMPT_MESSAGE = 'UPDATE_PROMPT_MESSAGE';
export const UPDATE_ACTIVE_STATUS = 'UPDATE_ACTIVE_STATUS';
export const ESCAPE_BATTLE = 'ESCAPE_BATTLE';