export const REDUCE_OPP_HEALTH = 'REDUCE_OPP_HEALTH';
export const REDUCE_USER_HEALTH = 'REDUCE_USER_HEALTH';
export const INITIAL_PROMPT = 'INITIAL_PROMPT';
export const UPDATE_ATTACK_PROMPT = 'UPDATE_ATTACK_PROMPT';
export const UPDATE_ACTIVE_STATUS = 'UPDATE_ACTIVE_STATUS';
export const ESCAPE_BATTLE = 'ESCAPE_BATTLE';

// Player
export const ADD_PLAYER_POKEMON = 'ADD_PLAYER_POKEMON';

// Opponent
export const ADD_OPP_POKEMON = 'ADD_OPP_POKEMON';

// Town
export const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';
