
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('pokemons').del()
    .then(function () {
      // Inserts seed entries
      return knex('pokemons').insert([
        { id: 1, name: 'Bulbasaur', type: 'Grass', health: 35, attackDamage: 5, attackName: 'Overgrow', rarity: 'common', evolves: 2 },
        { id: 2, name: 'Ivysaur', type: 'Grass', attackName: 'Razor Leaf', rarity: 'uncommon', evolves: 3 },
        { id: 3, name: 'Venusaur', type: 'Grass', attackName: 'Solar Beam', rarity: 'rare' },
        { id: 4, name: 'Charmander', type: 'Fire', health: 32, attackDamage: 4, attackName: 'Blaze', rarity: 'common', evolves: 5 },
        { id: 5, name: 'Charmeleon', type: 'Fire', attackName: 'Flamethrower', rarity: 'uncommon', evolves: 6 },
        { id: 6, name: 'Charizard', type: 'Fire', attackName: 'Inferno', rarity: 'rare' },
        { id: 7, name: 'Squirtle', type: 'Water', health: 38, attackDamage: 3, attackName: 'Water Gun', rarity: 'common', evolves: 8 },
        { id: 8, name: 'Wartortle', type: 'Water', attackName: 'Water Pulse', rarity: 'uncommon', evolves: 9 },
        { id: 9, name: 'Blastoise', type: 'Water', attackName: 'Hydro Pump', rarity: 'rare' },
        { id: 10, name: 'Caterpie', type: 'Bug', attackName: 'Tackle', rarity: 'common', evolves: 11 },
        { id: 11, name: 'Metapod', type: 'Bug', attackName: 'Tackle', rarity: 'uncommon', evolves: 12 },
        { id: 12, name: 'Butterfree', type: 'Bug', attackName: 'Whirlwind', rarity: 'rare' },
        { id: 13, name: 'Weedle', type: 'Bug', attackName: 'String Shot', rarity: 'common' },
        { id: 14, name: 'Kakuna', type: 'Bug', attackName: 'Bite', rarity: 'uncommon', evolves: 15 },
        { id: 15, name: 'Beedrill', type: 'Bug', attackName: 'Pin Missile', rarity: 'rare' },
        { id: 16, name: 'Pidgey', type: 'Flying', attackName: 'Gust', rarity: 'common', evolves: 17 },
        { id: 17, name: 'Pidgeotto', type: 'Flying', attackName: 'Twister', rarity: 'uncommon', evolves: 18 },
        { id: 18, name: 'Pidgeot', type: 'Flying', attackName: 'Hurricane', rarity: 'rare' },
        { id: 19, name: 'Rattata', type: 'Normal', attackName: 'Tail Whip', rarity: 'common', evolves: 20 },
        { id: 20, name: 'Raticate', type: 'Normal', attackName: 'Hyper Fang', rarity: 'rare' },
        { id: 21, name: 'Spearow', type: 'Flying', attackName: 'Peck', rarity: 'uncommon', evolves: 22 },
        { id: 22, name: 'Fearow', type: 'Flying', attackName: 'Aerial Ace', rarity: 'rare' },
        { id: 23, name: 'Ekans', type: 'Poison', attackName: 'Wrap', rarity: 'common', evolves: 24 },
        { id: 24, name: 'Arbok', type: 'Poison', attackName: 'Acid', rarity: 'uncommon' },
        { id: 25, name: 'Pikachu', type: 'Electric', attackName: 'Thunder Shock', rarity: 'uncommon', evolves: 26 },
        { id: 26, name: 'Raichu', type: 'Electric', attackName: 'Thunder Punch', rarity: 'rare' },
        { id: 27, name: 'Sandshrew', type: 'Ground', attackName: 'Scratch', rarity: 'uncommon', evolves: 28 },
        { id: 28, name: 'Sandslash', type: 'Ground', attackName: 'Earthquake', rarity: 'rare' },
        { id: 29, name: 'Nidoran-f', type: 'Poison', attackName: 'Scratch', rarity: 'common', evolves: 30 },
        { id: 30, name: 'Nidorina', type: 'Poison', attackName: 'Toxic Spikes', rarity: 'uncommon', evolves: 31 },
        { id: 31, name: 'Nidoqueen', type: 'Poison', attackName: 'Body Slam', rarity: 'rare' },
        { id: 32, name: 'Nidoran-m', type: 'Poison', attackName: 'Double Kick', rarity: 'common', evolves: 33 },
        { id: 33, name: 'Nidorino', type: 'Poison', attackName: 'Poison Jab', rarity: 'uncommon', evolves: 34 },
        { id: 34, name: 'Nidoking', type: 'Poison', attackName: 'Megahorn', rarity: 'rare' },
        { id: 35, name: 'Clefairy', type: 'Fairy', attackName: 'Moonblast', rarity: 'uncommon', evolves: 36 },
        { id: 36, name: 'Clefable', type: 'Fairy', attackName: 'Metronome', rarity: 'rare' },
        { id: 37, name: 'Vulpix', type: 'Fire', attackName: 'Fire Spin', rarity: 'uncommon', evolves: 38 },
        { id: 38, name: 'Ninetales', type: 'Fire', attackName: 'Heat Wave', rarity: 'rare' },
        { id: 39, name: 'Jigglypuff', type: 'Fairy', attackName: 'Sing', rarity: 'uncommon', evolves: 40 },
        { id: 40, name: 'Wigglytuff', type: 'Fairy', attackName: 'Sing', rarity: 'rare' },
        { id: 41, name: 'Zubat', type: 'Poison', attackName: 'Bite', rarity: 'uncommon', evolves: 42 },
        { id: 42, name: 'Golbat', type: 'Poison', attackName: 'Supersonic', rarity: 'rare' },
        { id: 43, name: 'Oddish', type: 'Grass', attackName: 'Absorb', rarity: 'common', evolves: 44 },
        { id: 44, name: 'Gloom', type: 'Grass', attackName: 'Petal Blizzard', rarity: 'uncommon', evolves: 45 },
        { id: 45, name: 'Vileplume', type: 'Grass', attackName: 'Solar Beam', rarity: 'rare' },
        { id: 46, name: 'Paras', type: 'Bug', attackName: 'Scratch', rarity: 'common', evolves: 47 },
        { id: 47, name: 'Parasect', type: 'Bug', attackName: 'Fury Cutter', rarity: 'rare' },
        { id: 48, name: 'Venonat', type: 'Bug', attackName: 'Poison Fang', rarity: 'common', evolves: 49 },
        { id: 49, name: 'Venomoth', type: 'Bug', attackName: 'Bug Buzz', rarity: 'rare' },
        { id: 50, name: 'Diglett', type: 'Ground', attackName: 'Mud-Slap', rarity: 'common', evolves: 51 },
        { id: 51, name: 'Dugtrio', type: 'Ground', attackName: 'Fissure', rarity: 'rare' },
        { id: 52, name: 'Meowth', type: 'Normal', attackName: 'Slash', rarity: 'uncommon', evolves: 53 },
        { id: 53, name: 'Persian', type: 'Normal', attackName: 'Fury Swipes', rarity: 'rare' },
        { id: 54, name: 'Psyduck', type: 'Water', attackName: 'Water Gun', rarity: 'uncommon', evolves: 55 },
        { id: 55, name: 'Golduck', type: 'Water', attackName: 'Hydro Pump', rarity: 'rare' },
        { id: 56, name: 'Mankey', type: 'Fighting', attackName: 'Low Kick', rarity: 'uncommon', evolves: 57 },
        { id: 57, name: 'Primeape', type: 'Fighting', attackName: 'Close Combat', rarity: 'rare' },
        { id: 58, name: 'Growlithe', type: 'Fire', attackName: 'Ember', rarity: 'uncommon', evolves: 59 },
        { id: 59, name: 'Arcanine', type: 'Fire', attackName: 'Fire Blitz', rarity: 'rare' },
        { id: 60, name: 'Poliwag', type: 'Water', attackName: 'Bubble', rarity: 'common', evolves: 61 },
        { id: 61, name: 'Poliwhirl', type: 'Water', attackName: 'Rain Dance', rarity: 'uncommon', evolves: 62 },
        { id: 62, name: 'Poliwrath', type: 'Water', attackName: 'Bubble Beam', rarity: 'rare' },
        { id: 63, name: 'Abra', type: 'Phychic', attackName: 'Psyshock', rarity: 'common', evolves: 64 },
        { id: 64, name: 'Kadabra', type: 'Phychic', attackName: 'Psychic', rarity: 'uncommon', evolves: 65 },
        { id: 65, name: 'Alakazam', type: 'Phychic', attackName: 'Future Sight', rarity: 'rare' },
        { id: 66, name: 'Machop', type: 'Fighting', attackName: 'Karate Chop', rarity: 'common', evolves: 67 },
        { id: 67, name: 'Machoke', type: 'Fighting', attackName: 'Vital Throw', rarity: 'uncommon', evolves: 68 },
        { id: 68, name: 'Machamp', type: 'Fighting', attackName: 'Dynamic Punch', rarity: 'rare' },
        { id: 69, name: 'Bellsprout', type: 'Grass', attackName: 'Vine Whip', rarity: 'common', evolves: 70 },
        { id: 70, name: 'Weepinbell', type: 'Grass', attackName: 'Razor Leaf', rarity: 'uncommon', evolves: 71 },
        { id: 71, name: 'Victreebel', type: 'Grass', attackName: 'Leaf Storm', rarity: 'rare' },
        { id: 72, name: 'Tentacool', type: 'Water', attackName: 'Water Pulse', rarity: 'uncommon', evolves: 73 },
        { id: 73, name: 'Tentacruel', type: 'Water', attackName: 'Hydro Pump', rarity: 'rare' },
        { id: 74, name: 'Geodude', type: 'Rock', attackName: 'Rollout', rarity: 'common', evolves: 75 },
        { id: 75, name: 'Graveler', type: 'Rock', attackName: 'Earthquake', rarity: 'uncommon', evolves: 76 },
        { id: 76, name: 'Golem', type: 'Rock', attackName: 'Stone Edge', rarity: 'rare' },
        { id: 77, name: 'Ponyta', type: 'Fire', attackName: 'Fire Spin', rarity: 'uncommon', evolves: 78 },
        { id: 78, name: 'Rapidash', type: 'Fire', attackName: 'Flame Charge', rarity: 'rare' },
        { id: 79, name: 'Slowpoke', type: 'Water', attackName: 'Water Gun', rarity: 'uncommon' },
        { id: 80, name: 'Slowbro', type: 'Water', attackName: 'Rain Dance', rarity: 'rare' },
        { id: 81, name: 'Magnemite', type: 'Electric', attackName: 'Thunder Shock', rarity: 'uncommon', evolves: 82 },
        { id: 82, name: 'Magneton', type: 'Electric', attackName: 'Spark', rarity: 'rare' },
        { id: 83, name: "Farfetch'd", type: 'Normal', attackName: 'Air Slash', rarity: 'rare' },
        { id: 84, name: "Doduo", type: 'Normal', attackName: 'Pluck', rarity: 'uncommon', evolves: 85 },
        { id: 85, name: "Dodrio", type: 'Normal', attackName: 'Drill Peck', rarity: 'rare' },
        { id: 86, name: "Seel", type: 'Water', attackName: 'Aqua Jet', rarity: 'uncommon', evolves: 87 },
        { id: 87, name: "Dewgong", type: 'Water', attackName: 'Hail', rarity: 'rare' },
        { id: 88, name: "Grimer", type: 'Poison', attackName: 'Sludge Bomb', rarity: 'uncommon', evolves: 89 },
        { id: 89, name: "Muk", type: 'Poison', attackName: 'Belch', rarity: 'rare' },
        { id: 90, name: "Shellder", type: 'Water', attackName: 'Clamp', rarity: 'uncommon', evolves: 91 },
        { id: 91, name: "Cloyster", type: 'Water', attackName: 'Spike Cannon', rarity: 'rare' },
        { id: 92, name: "Gastly", type: 'Ghost', attackName: 'Shadow Ball', rarity: 'common', evolves: 93 },
        { id: 93, name: "Haunter", type: 'Ghost', attackName: 'Hex', rarity: 'uncommon', evolves: 94 },
        { id: 94, name: "Gengar", type: 'Ghost', attackName: 'Nightmare', rarity: 'rare' },
        { id: 95, name: "Onix", type: 'Rock', attackName: 'Rock Slide', rarity: 'rare' },
        { id: 96, name: "Drowzee", type: 'Psychic', attackName: 'Psybeam', rarity: 'uncommon', evolves: 97 },
        { id: 97, name: "Hypno", type: 'Psychic', attackName: 'Zen Headbutt', rarity: 'rare' },
        { id: 98, name: "Krabby", type: 'Water', attackName: 'Crabhammer', rarity: 'uncommon', evolves: 99 },
        { id: 99, name: "Kingler", type: 'Water', attackName: 'Bubble Beam', rarity: 'rare' },
        { id: 100, name: "Voltorb", type: 'Electric', attackName: 'Spark', rarity: 'uncommon', evolves: 101 },
        { id: 101, name: "Electrode", type: 'Electric', attackName: 'Discharge', rarity: 'rare' },
        { id: 102, name: "Exeggcute", type: 'Grass', attackName: 'Bullet Seed', rarity: 'uncommon', evolves: 103 },
        { id: 103, name: "Exeggutor", type: 'Grass', attackName: 'Leaf Storm', rarity: 'rare' },
        { id: 104, name: "Cubone", type: 'Ground', attackName: 'Bonemerang', rarity: 'uncommon', evolves: 105 },
        { id: 105, name: "Marowak", type: 'Ground', attackName: 'Bone Rush', rarity: 'rare' },
        { id: 106, name: "Hitmonlee", type: 'Fighting', attackName: 'High Jump Kick', rarity: 'rare' },
        { id: 107, name: "Hitmonchan", type: 'Fighting', attackName: 'Focus Punch', rarity: 'rare' },
        { id: 108, name: "Lickitung", type: 'Normal', attackName: 'Thrash', rarity: 'uncommon' },
        { id: 109, name: "Koffing", type: 'Poison', attackName: 'Belch', rarity: 'uncommon', evolves: 110 },
        { id: 110, name: "Weezing", type: 'Poison', attackName: 'Sludge Bomb', rarity: 'rare' },
        { id: 111, name: "Rhyhorn", type: 'Ground', attackName: 'Rock Blast', rarity: 'uncommon', evolves: 112 },
        { id: 112, name: "Rhydon", type: 'Ground', attackName: 'Horn Drill', rarity: 'rare' },
        { id: 113, name: "Chansey", type: 'Normal', attackName: 'Egg Bomb', rarity: 'rare' },
        { id: 114, name: "Tangela", type: 'Grass', attackName: 'Power Whip', rarity: 'uncommon' },
        { id: 115, name: "Kangaskhan", type: 'Normal', attackName: 'Sucker Punch', rarity: 'rare' },
        { id: 116, name: "Horsea", type: 'Water', attackName: 'Bubble', rarity: 'uncommon', evolves: 117 },
        { id: 117, name: "Seadra", type: 'Water', attackName: 'Hydro Pump', rarity: 'rare' },
        { id: 118, name: "Goldeen", type: 'Water', attackName: 'Waterfall', rarity: 'uncommon', evolves: 119 },
        { id: 119, name: "Seaking", type: 'Water', attackName: 'Soak', rarity: 'rare' },
        { id: 120, name: "Staryu", type: 'Water', attackName: 'Bubble Beam', rarity: 'uncommon', evolves: 121 },
        { id: 121, name: "Starmie", type: 'Water', attackName: 'Water Gun', rarity: 'rare' },
        { id: 122, name: "Mr. Mime", type: 'Psychic', attackName: 'Psybeam', rarity: 'rare' },
        { id: 123, name: "Scyther", type: 'Bug', attackName: 'Air Slash', rarity: 'rare' },
        { id: 124, name: "Jynx", type: 'Ice', attackName: 'Avalanche', rarity: 'uncommon' },
        { id: 125, name: "Electabuzz", type: 'Electric', attackName: 'Thunderbolt', rarity: 'uncommon' },
        { id: 126, name: "Magmar", type: 'Fire', attackName: 'Lava Plume', rarity: 'uncommon' },
        { id: 127, name: "Pinsir", type: 'Bug', attackName: 'Guillotine', rarity: 'uncommon' },
        { id: 128, name: "Tauros", type: 'Normal', attackName: 'Thrash', rarity: 'uncommon' },
        { id: 129, name: "Magikarp", type: 'Water', attackName: 'Tackle', rarity: 'common', evolves: 130 },
        { id: 130, name: "Gyarados", type: 'Water', attackName: 'Hurricane', rarity: 'rare' },
        { id: 131, name: "Lapras", type: 'Water', attackName: 'Ice Beam', rarity: 'rare' },
        { id: 132, name: "Ditto", type: 'Normal', attackName: 'Transform', rarity: 'common' },
        { id: 133, name: "Eevee", type: 'Normal', attackName: 'Tackle', rarity: 'common', evolves: 134 },
        { id: 134, name: "Vaporeon", type: 'Water', attackName: 'Aqua Ring', rarity: 'rare', evolves: 135 },
        { id: 135, name: "Jolteon", type: 'Electric', attackName: 'Thunder Wave', rarity: 'rare', evolves: 136 },
        { id: 136, name: "Flareon", type: 'Fire', attackName: 'Flare Blitz', rarity: 'rare' },
        { id: 137, name: "Porygon", type: 'Normal', attackName: 'Tri Attack', rarity: 'uncommon' },
        { id: 138, name: "Omanyte", type: 'Rock', attackName: 'Rollout', rarity: 'uncommon', evolves: 139 },
        { id: 139, name: "Omastar", type: 'Rock', attackName: 'Rock Blast', rarity: 'rare' },
        { id: 140, name: "Kabuto", type: 'Rock', attackName: 'Sand Attack', rarity: 'uncommon', evolves: 141 },
        { id: 141, name: "Kabutops", type: 'Rock', attackName: 'Night Slash', rarity: 'rare' },
        { id: 142, name: "Aerodactyl", type: 'Rock', attackName: 'Hyper Beam', rarity: 'rare' },
        { id: 143, name: "Snorlax", type: 'Normal', attackName: 'Crunch', rarity: 'rare' },
        { id: 144, name: "Articuno", type: 'Ice', attackName: 'Blizzard', rarity: 'rare' },
        { id: 145, name: "Zapdos", type: 'Electric', attackName: 'Zap Cannon', rarity: 'rare' },
        { id: 146, name: "Moltres", type: 'Fire', attackName: 'Heat Wave', rarity: 'rare' },
        { id: 147, name: "Dratini", type: 'Dragon', attackName: 'Twister', rarity: 'common', evolves: 148 },
        { id: 148, name: "Dragonair", type: 'Dragon', attackName: 'Dragon Rage', rarity: 'uncommon', evolves: 149 },
        { id: 149, name: "Dragonite", type: 'Dragon', attackName: 'Outrage', rarity: 'rare' },
        { id: 150, name: "Mewtwo", type: 'Psychic', attackName: 'Psystrike', rarity: 'rare' },
        { id: 151, name: "Mew", type: 'Psychic', attackName: 'Aura Sphere', rarity: 'rare' },
      ]);
    });
};
